# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1430303354);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1430300591);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1430310967);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1430300471);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 2216);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140621185158");
user_pref("browser.startup.homepage_override.mstone", "24.5.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1429272786953");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1430310068401");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1430310070259");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1430396470259");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1428701386354");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1428730223847");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1428658152885");
user_pref("datareporting.sessions.current.activeTicks", 20);
user_pref("datareporting.sessions.current.firstPaint", 406);
user_pref("datareporting.sessions.current.main", 40);
user_pref("datareporting.sessions.current.sessionRestored", 425);
user_pref("datareporting.sessions.current.startTime", "1428906846837");
user_pref("datareporting.sessions.current.totalTime", 2084);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("extensions.blocklist.pingCountTotal", 21);
user_pref("extensions.blocklist.pingCountVersion", 21);
user_pref("extensions.bootstrappedAddons", "{\"langpack-zh-CN@firefox.mozilla.org\":{\"version\":\"24.5.0\",\"type\":\"locale\",\"descriptor\":\"/root/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-zh-CN@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.5.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1428676425000,\"rdfTime\":1403377993000}}},{\"name\":\"app-system-user\",\"addons\":{\"langpack-zh-CN@firefox.mozilla.org\":{\"descriptor\":\"/root/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-zh-CN@firefox.mozilla.org.xpi\",\"mtime\":1403378027000}}}]");
user_pref("extensions.lastAppVersion", "24.5.0");
user_pref("extensions.lastPlatformVersion", "24.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140621185158");
user_pref("gecko.mstone", "24.5.0");
user_pref("idle.lastDailyNotification", 1430312251);
user_pref("intl.charsetmenu.browser.cache", "gbk, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1430310068);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1428661843);
user_pref("toolkit.startup.last_success", 1428906846);
user_pref("toolkit.telemetry.previousBuildID", "20140621185158");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1431499018);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
